FROM golang:1.22-alpine AS builder

WORKDIR /app
RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN GONOSUMDB='*' GOPROXY='direct' go mod download

COPY . .
RUN GONOSUMDB='*' GOPROXY='direct' CGO_ENABLED=0 \
    go build -mod=mod -ldflags="-s -w" \
    -o xtunnel-server ./server/cmd

FROM alpine:3.20
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=builder /app/xtunnel-server .
COPY configs/ configs/

EXPOSE 7001
CMD ["./xtunnel-server", "--config", "configs/server.json"]